---
version: "3.9"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: on-failure

    volumes:
      - ${DATA_ROOT:-/mnt/data}/vaultwarden:/data

    ports:
      - "${VAULTWARDEN_PORT:-80}:80"
