services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # SECURITY NOTE: In a rootless Podman environment, "0" maps to the unprivileged
    # host user. If running in rootful Docker, change this to your PUID:PGID.
    user: "0"
    ports:
      - '${GRAFANA_PORT:-3000}:3000'
    volumes:
      - ${DATA_ROOT:-/mnt/data}/grafana/data:/var/lib/grafana
      - ${DATA_ROOT:-/mnt/data}/grafana/conf/grafana.ini:/etc/grafana/grafana.ini
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # SECURITY NOTE: In a rootless Podman environment, "0" maps to the unprivileged
    # host user. If running in rootful Docker, change this to your PUID:PGID.
    user: "0"
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    restart: on-failure
    volumes:
      - ${DATA_ROOT:-/mnt/data}/prometheus:/etc/prometheus:ro
      - ${DATA_ROOT:-/mnt/data}/prometheus/data:/prometheus
