---
services:
    fmd:
        # Use the prebuilt image
        image: registry.gitlab.com/fmd-foss/fmd-server:0.14.0
        # Or build the image yourself (note the leading 'v')
        # build: https://gitlab.com/fmd-foss/fmd-server.git#v0.14.0
        container_name: fmd
        env_file:
            - .env
        ports:
            - "0.0.0.0:49152:8080"
        volumes:
            - '/srv/fmd-server/fmddata/db/:/var/lib/fmd-server/db/'
        restart: unless-stopped
